dataset: 
    split:
        cross_domain: 
            train: ["BRD", "FLW", "BCT", "CRS", "SPT"]
            validation: ["DOG", "PLT_NET", "PNU", "APL", "ACT_40"]
            test: ["AWA", "FNG", "PRT", "BTS", "ACT_410"]
        domain_independent: 
            train: ["PLK", "INS_2", "RESISC", "RSICB", "MD_MIX", "MD_5_BIS"]
            validation: ["PLT_VIL", "MED_LF", "TEX", "TEX_DTD"]
            test: ["AWA", "FNG", "PRT", "BTS", "ACT_410"]
    train: 
        batch_size: 16
        n_ways:
            value: 5
        k_shots: 
            value: 15
        query_size: 20
    validation: 
        n_ways:
            value: 5
        k_shots: 
            value: 15
        query_size: 20
model: 
    number_of_batches: 10_000
    number_of_training_tasks: 10_000
    number_of_validation_tasks_per_dataset: 10
    validate_every: 100
    dropout_probability: 0.30