dataset: 
    test: 
        n_ways:
            value: 5
        k_shots: 
            value: 1
        query_size: 20
            
evaluation5000:
        tasks_per_dataset: 250
        confidence_estimators:
            use: "GTConfidenceEstimator"
            ConstantConfidenceProvider:
                confidence: 0
            GTConfidenceEstimator: {} 
            MCDropoutConfidenceEstimator:
                num_samples: 100

        augmentors:
            use: "GenerativeAugmentation"
            PseudoAugmentation: 
                keep_original_data: True
                augmentation_size: 
                    scale: 1
                    offset: 3 
                    maximum: 20
                    threshold: 0.8
            StandardAugmentation:
                keep_original_data: True
                augmentation_size:
                    scale: 1
                    offset: 3 
                    maximum: 20
                    threshold: 0.8
            GenerativeAugmentation:
                keep_original_data: True
                augmentation_size: 
                    scale: 1
                    offset: 3 
                    maximum: 20
                    threshold: 0.8
                annotator_type: "hed"
    