dataset: 
    test: 
        n_ways:
            value: 5
        k_shots: 
            value: 11 # 10 samples are used for pseudo confidence estimation
        query_size: 20

evaluation:
    tasks_per_dataset: 200
    confidence_estimators:
        use: "PseudoConfidenceEstimator"
        PseudoConfidenceEstimator: {} 

    augmentors:
        use: StandardAugmentation
        StandardAugmentation:
            keep_original_data: True
            augmentation_size: 
                scale: 1
                offset: 3
                maximum: 20
                threshold: 0.8