dataset: 
    test: 
        n_ways:
            value: 5
        k_shots: 
            value: 10
        query_size: 20

evaluation:
    tasks_per_dataset: 200
    confidence_estimators:
        use: "MCDropoutConfidenceEstimator"
        MCDropoutConfidenceEstimator:
            num_samples: 100

    augmentors:
        use: GenerativeAugmentation
        GenerativeAugmentation:
            keep_original_data: True
            augmentation_size: 
                scale: 1
                offset: 3 
                maximum: 20
                threshold: 0.8
            annotator_type: "hed"