dataset: 
    test: 
        n_ways:
            value: 5
        k_shots: 
            value: 11 # 10 samples are used for pseudo augmentation
        query_size: 20

evaluation:
    tasks_per_dataset: 200
    confidence_estimators:
        use: "GTConfidenceEstimator"
        GTConfidenceEstimator: {} 

    augmentors:
        use: PseudoAugmentation
        PseudoAugmentation:
            keep_original_data: True
            augmentation_size: 
                scale: 1
                offset: 3 
                maximum: 20
                threshold: 0.8