dataset: 
    test: 
        n_ways:
            value: 5
        k_shots: 
            value: 20
        query_size: 20

evaluation:
    tasks_per_dataset: 100
    confidence_estimators:
        use: "ConstantConfidenceProvider"
        ConstantConfidenceProvider:
            confidence: 1
        PseudoConfidenceEstimator: {}
        MCDropoutConfidenceEstimator:
            num_samples: 20

    augmentors:
        use: null
        PseudoAugmentation:
            threshold: 0.75
            scale: 2
            keep_original_data: True
        StandardAugmentation:
            threshold: 0.75
            scale: 2
            keep_original_data: True
            rotation: 25
            flip: True
        GenerativeAugmentation:
            threshold: 0.75
            scale: 2
            keep_original_data: True