dataset: 
    test: 
        n_ways:
            value: 5
        k_shots: 
            value: 10
        query_size: 20

evaluation:
    tasks_per_dataset: 1000
    confidence_estimators:
        use: "ConstantConfidenceProvider"
        ConstantConfidenceProvider:
            confidence: 1
            
    augmentors:
        use: null