dataset: 
    test: 
        n_ways:
            value: 5
        k_shots: 
            range: [1, 20]
        query_size: 20

evaluation:
    tasks_per_dataset: 1000
    confidence_estimators:
        use: "ConstantConfidenceProvider"
        ConstantConfidenceProvider:
            confidence: 1

    augmentors:
        use: null