dataset: 
    test: 
        n_ways:
            value: 5
        k_shots: 
            value: 1
        query_size: 20

evaluation:
    tasks_per_dataset: 200
    confidence_estimators:
        use: "ConstantConfidenceProvider"
        ConstantConfidenceProvider:
            confidence: 1

    augmentors:
        use: null