dataset: 
    test: 
        n_ways:
            value: 5
        k_shots: 
            value: 20 # 10 samples are and pseudo augmentation
        query_size: 10

evaluation:
    tasks_per_dataset: 50
    confidence_estimators:
        use: "ConstantConfidenceProvider"
        ConstantConfidenceProvider:
            confidence: 0

    augmentors:
        use: PseudoAugmentation
        PseudoAugmentation:
            keep_original_data: True
            augmentation_size: 
                scale: 1
                offset: 3 
                maximum: 20
                threshold: 0.8