dataset: 
    test: 
        n_ways:
            value: 5
        k_shots: 
            choice: [1, 5, 10, 15, 20]
        query_size: 20

evaluation:
    tasks_per_dataset: 500
    confidence_estimators:
        use: "ConstantConfidenceProvider"
        ConstantConfidenceProvider:
            confidence: 0
        PseudoConfidenceEstimator: {}
        MCDropoutConfidenceEstimator:
            num_samples: 20

    augmentors:
        use: StandardAugmentation
        StandardAugmentation:
            threshold: 0.75
            keep_original_data: True
            augmentation_size: 
                scale: 2
                offset: 5 
                maximum: 20