dataset: 
    batch_size: 16
    n_ways:
        value: 5
    k_shots: 
        range: [1, 20]
    query_size: 20
model: 
    number_of_batches: 10000
    number_of_training_tasks: 10000
    number_of_validation_tasks_per_dataset: 20
    validate_every: 100
