dataset: 
    test: 
        n_ways:
            value: 5
        k_shots: 
            value: 10
        query_size: 20

evaluation:
    tasks_per_dataset: 10
    confidence_estimators:
        use: "ConstantConfidenceProvider"
        ConstantConfidenceProvider:
            confidence: 0
        PseudoConfidenceEstimator: {}
        MCDropoutConfidenceEstimator:
            num_samples: 20

    augmentors:
        use: GenerativeAugmentation
        GenerativeAugmentation:
            keep_original_data: True
            augmentation_size: 
                scale: 1
                offset: 5 
                maximum: 20
                threshold: 0.8
            annotator_type: "hed"